
sonar.projectKey=proyecto_web_backend
sonar.projectName=Proyecto Web Backend
sonar.sourceEncoding=UTF-8


sonar.sources=.


sonar.inclusions=**/*.py


sonar.exclusions=**/venv/**,**/__pycache__/**,**/migrations/**


sonar.host.url=http://localhost:9000


sonar.login=squ_d81eca96b7de0122452d69cc3bc1593b9381120b
